version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
        VAULT_ADDR: "http://192.168.99.100:8200"
        VAULT_DEV_ROOT_TOKEN_ID: "934f9eae-31ff-a8ef-e1ca-4bea9e07aa09"
  setup-vault:
    image: vault
    container_name: setup-vault
    entrypoint: /bin/sh
    volumes:
      - './config:/config'
    environment:
        VAULT_ADDR: 'http://vault:8200'
        CONFIG_DIR: '/config'
    command: >
            -c "
            sleep 2;
            /config/vault-init.sh;
            "
    depends_on:
            - vault