version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  vault:
    image: vault
    container_name: vault_dev
    ports:
      - "127.0.0.1:8200:8200"
    cap_add:
      - IPC_LOCK